### ISSUE TITLE
Article vs Website og:type

### ISSUE THREAD

**Issue by Jolg42** [HackerLoop/metatags-101#2]
Hey !

I think the most common usage of og:type is 'website' for basic websites, not 'article' which is more complex ! ping @squirelo 

See [https://developers.facebook.com/docs/opengraph/howtos/maximizing-distribution-media-content](https://developers.facebook.com/docs/opengraph/howtos/maximizing-distribution-media-content)

>og:type - Different types of media will change how your content shows up in Facebook's newsfeed. There are a number of different common object types already defined. If you don't specify a type, the default will be website. You can also specify your own types via Open Graph.

**Comment by squirelo** [comment]
Done.

Thank you @Jolg42! Yes it's a shame, one year later ^^
